services:
  postgres:
    image: postgres:16-alpine
    container_name: loomi-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: loomi_user
      POSTGRES_PASSWORD: loomi_password
      POSTGRES_DB: loomi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U loomi_user -d loomi_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

