services:
  # Database PostgreSQL (Development)
  postgres:
    image: postgres:16-alpine
    container_name: loomi-postgres-dev
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: loomi_user
      POSTGRES_PASSWORD: loomi_password
      POSTGRES_DB: loomi_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U loomi_user -d loomi_db']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loomi-network-dev

  # Cache Redis (Development)
  redis:
    image: redis:7-alpine
    container_name: loomi-redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loomi-network-dev

  # Message Broker RabbitMQ (Development)
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: loomi-rabbitmq-dev
    restart: unless-stopped
    ports:
      - '5672:5672'   # AMQP protocol
      - '15672:15672' # Management UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: loomi_user
      RABBITMQ_DEFAULT_PASS: loomi_password
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loomi-network-dev

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local
  rabbitmq_data_dev:
    driver: local

networks:
  loomi-network-dev:
    driver: bridge

